<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use JosephLeedy\CustomFees\ViewModel\CustomFees as CustomFeesViewModel;

/** @var HyvaCsp $hyvaCsp */
/** @var ViewModelRegistry $viewModels */

/** @var CustomFeesViewModel $customFeesViewModel */
$customFeesViewModel = $viewModels->require(CustomFeesViewModel::class);

/**
 * The AlpineJS scope of this file is the method `initCartTotals()` in Magento_Checkout::php-cart/totals.phtml
 */
?>
<script>
    function initCustomFeesTotalSegment() {
        return {
            /**
             *  @var {[{code: string, title: string, value: number}]}
             */
            customFees: <?= /* @noEscape */ $customFeesViewModel->getCustomFeesAsJson() ?>,
            /**
             * @returns {boolean}
             */
            isCustomFeesTotalSegment() {
                const isCustomFee = Object.values(this.customFees)
                    .some(customFee => customFee.code === this.segment.code);

                return isCustomFee && this.segment.value > 0;
            },
            /**
             * @returns {string}
             */
            getCustomFeeTitle()
            {
                return this.segment.title;
            },
            /**
             * @returns {string}
             */
            getFormattedCustomFeeValue()
            {
                return hyva.formatPrice(this.segment.value);
            },
        };
    }

    window.addEventListener(
        'alpine:init',
        () => Alpine.data('initCustomFeesTotalSegment', initCustomFeesTotalSegment),
        {once: true}
    );
</script>
<?php isset($hyvaCsp) && $hyvaCsp->registerInlineScript() ?>
