<div x-data="initCustomFeesTotalSegment">
    <template x-if="isCustomFeesTotalSegment">
        <div class="flex pb-2 my-2 border-b text-md lg:text-sm md:grid md:grid-cols-2 md:w-full border-container">
            <div class="w-7/12 text-left md:w-auto" x-html="getCustomFeeTitle"></div>
            <div class="w-5/12 text-right md:w-auto" x-text="getFormattedCustomFeeValue"></div>
        </div>
    </template>
</div>
